on: [push]

jobs:
  testactions_job:
    runs-on: ubuntu-latest
    name: A job to test the multi architecture actions
    steps:
    - name: Setup MultiArch
      id: setup-multi
      uses: uraimo/multiarch-actions/setup-multiarch@master
    - name: Run some commands on arm64
      id: runcmd
      uses: uraimo/multiarch-actions/run-on-arch@master
      with:
        run: |
            uname -a
            free
            echo "Done."
    - name: Get the output
      run: echo "The output was ${{ steps.runcmd.outputs.out }}"
