on: [push]

jobs:
  testactions_job:
    runs-on: ubuntu-18.04
    name: A job to test the multi architecture actions
    steps:
    - name: Setup MultiArch
      uses: uraimo/multiarch-actions/setup-multiarch@master
    - name: Build with Swift on armv7
      uses: uraimo/multiarch-actions/run-on-arch@master
      with:
        run: |
          wget https://github.com/uraimo/buildSwiftOnARM/releases/download/5.0.3/swift-5.0.3-armv7-Ubuntu1804.tgz
          tar xzf swift-5.0.3-armv7-Ubuntu1804.tgz
          echo "import Glibc\n\nprint(\"Test!\")" > test.swift
          ./usr/bin/swift run test.swift
